### ISSUE TITLE
Featured works - Thumbnails?

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#124]
The thumbnails seem to work for some, but not all featured words / recently uploaded works. Can we fix this?

<img width="1194" alt="Screenshot 2019-04-03 at 14 46 24" src="https://user-images.githubusercontent.com/40735172/55483951-7f3a1a80-561f-11e9-9f84-0583c7d74e2b.png">

**Comment by yf508** [comment]
There are various reasons for thumbnails not being generated, e.g.:
1) dialects in filename, e.g. in [this resource](https://resources.ncelp.org/concern/resources/kw52j8067?locale=en). Remove dialects from the filename will fix this problem.
2) other system problems terminated the thumbnail generation process, e.g. the system was restarted during the generation process.
3) I've updated system to support thumbnail generation from MS office files.

@IAlferink please test if it works now.

**Comment by yf508** [comment]
1 more problem found: currently all derivatives are stored with the APP_FOLDER/tmp/derivatives so after a new deployment the thumbnails won't be available.

**Comment by IAlferink** [comment]
@yf508 this seems to work now. It takes a little while for the thumbnails to become visible, but they do  work.
