### ISSUE TITLE
Unable to feature work

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#153]
Presumably related to #131. For most works the _Feature_ option works fine, but for some I can't manage to do it. I've tried in Safari and Chrome. Both the feature and unfeature buttons appear at the same time and clicking them doesn't result in featuring / unfeaturing:
<img width="1211" alt="Screenshot 2019-05-02 at 09 48 00" src="https://user-images.githubusercontent.com/40735172/57065106-45147500-6cc0-11e9-8b92-93c07c262183.png">

**Comment by yf508** [comment]
Related Hyrax issue: https://github.com/samvera/hyrax/issues/3169
