### ISSUE TITLE
Edit function through dashboard does not work

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#156]
On the dashboard in the _Works_ section you can select a Resource and click on _edit selected_. However, when you do you receive an error message. You can also get to the editing page through the Resource Details page, so we can edit works if we need to.
<img width="1431" alt="Screenshot 2019-05-10 at 10 53 18" src="https://user-images.githubusercontent.com/40735172/57518808-d499d380-7311-11e9-8cad-ffd2a5f9d0a8.png">

**Comment by paluchas** [comment]
Seems to work now. I tested on staging system All Works -> Edit.
