### ISSUE TITLE
Text change in upload form

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#157]
Please change the text for the OASIS links on the upload form to:

Please, enter the link to one or more OASIS summaries which explain the research principles behind this resource.  Go on [www.oasis-database.org](www.oasis-database.org) to find a summary and copy the link to the field below.
<img width="776" alt="Screenshot 2019-05-13 at 07 28 54" src="https://user-images.githubusercontent.com/40735172/57600120-d1d8f180-7550-11e9-9db9-37bea1d6505a.png">

**Comment by paluchas** [comment]
@IAlferink What about IRIS links field? Are the instruction correct?

**Comment by IAlferink** [comment]
@paluchas Yes, the IRIS instructions are correct.

**Comment by IAlferink** [comment]
@paluchas And could you please make this text change as well?

**Comment by websnacks** [comment]
Text change has been made. It will push to live as soon as possible.
