### ISSUE TITLE
Text change Resource Details page

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#167]
@paluchas This is the other text change
On the _Resource Details_ page please change _Items_ to _Items to download_.
<img width="620" alt="Screenshot 2019-06-20 at 16 21 03" src="https://user-images.githubusercontent.com/40735172/59860982-d7a7cb00-9377-11e9-8456-a14389e5a0df.png">

**Comment by IAlferink** [comment]
@paluchas Could you please make this change?

**Comment by websnacks** [comment]
Done, waiting for code review and merge into development.
