### ISSUE TITLE
Clean up Download page

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#169]
The download page has a lot of information that is not very useful for the teachers, so I'd like to clean it up. Can you please
1. Make the download button bigger
2. Remove all the info in the square boxes
<img width="1227" alt="Screenshot 2019-07-03 at 14 10 02" src="https://user-images.githubusercontent.com/40735172/60602135-23f8ff00-9dab-11e9-87ce-64b4f461097a.png">

**Comment by IAlferink** [comment]
@paluchas Emma is really to do this asap. Is there any Sebastiaan could look at this?

**Comment by websnacks** [comment]
@IAlferink @paluchas 

I changed the buttons so now these are more noticeable.

**Comment by IAlferink** [comment]
@websnacks Looks better. Could we move the _Date modified_ to appear under _Date uploaded_?
<img width="1348" alt="Screenshot 2019-08-22 at 12 48 00" src="https://user-images.githubusercontent.com/40735172/63521654-c8b3d500-c4ee-11e9-95e8-d010c5773a59.png">

Also, could we make the term _File Details_ smaller. Or even remove it?

**Comment by websnacks** [comment]
Done. I cleaned up the page as well.. removing the unnecessary padding around the social media buttons.

**Comment by IAlferink** [comment]
Thanks! Can you push these changes to production?

**Comment by IAlferink** [comment]
@paluchas I think this issue can be closed.
