### ISSUE TITLE
Make collections functional

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#184]
We want to be able to use the collections feature on the Resource Portal. For this we need the following changes to be made:

**1. Add an _Add to collection_ button on the Resource details page (in the circled row below).**
<img width="1342" alt="Screenshot 2019-08-02 at 14 32 44" src="https://user-images.githubusercontent.com/40735172/62373948-ccc58600-b532-11e9-9c53-908340f886c6.png">

**2. Make collections discoverable.** They are set to discoverable in the collection type settings, but visibility as a facet has been disabled.

**3.  Add collections to the homepage.** Maybe we could have something like below with our _Featured Works_ - TBC
<img width="701" alt="Screenshot 2019-08-02 at 14 37 41" src="https://user-images.githubusercontent.com/40735172/62374145-29c13c00-b533-11e9-8db1-dbd7933ab86d.png">

**4. Make some aesthetic changes to the Collection page view.**
Default: https://test-resources.ncelp.org/collections/6q182k21g?locale=en
Mock up

<img width="985" alt="DC267995-71CA-4659-9001-BEDC270335C3" src="https://user-images.githubusercontent.com/40735172/62374446-e61b0200-b533-11e9-8c56-80c6e17314fd.png">

**Comment by IAlferink** [comment]
@yf508 Could you give us an estimate on how long it would take to do this work?

**Comment by IAlferink** [comment]
@yf508 Could you have a look, please?

**Comment by yf508** [comment]
@IAlferink start working on it.

**Comment by IAlferink** [comment]
@yf508 @websnacks 
Can we change the colour scheme? _Explore collections_ is not visible unless you hover over it.
<img width="1273" alt="Screenshot 2019-08-28 at 12 32 24" src="https://user-images.githubusercontent.com/40735172/63854477-2768cb00-c995-11e9-8b3d-6e55e301e0dd.png">
 
Similarly, when you click on _Explore collections_ text in the blue rows is not visible.
<img width="513" alt="Screenshot 2019-08-28 at 13 11 23" src="https://user-images.githubusercontent.com/40735172/63854575-5a12c380-c995-11e9-85cb-f744ac949698.png">

I think the way it looked last week was clearer:
<img width="1302" alt="Screenshot 2019-08-22 at 12 02 19" src="https://user-images.githubusercontent.com/40735172/63854669-97775100-c995-11e9-98b1-759d2c46b44f.png">

**Comment by IAlferink** [comment]
@yf508 @websnacks Also, wondering about this question [#193](#193). We'll have a nested structure for the collections, so it would be good if we could have only the top-level ones highlighted.

**Comment by yf508** [comment]
@IAlferink The display issue has been resolved. #193 is not a quick one as it's not supported by Hyrax. I'm investigating the possibilities.
