### ISSUE TITLE
Error when clicking on 'view all collections'

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#190]
When I click on _View all collections_  on the homepage. I get the following error message:
<img width="1251" alt="Screenshot 2019-08-22 at 12 04 27" src="https://user-images.githubusercontent.com/40735172/63509999-669aa600-c4d5-11e9-8040-f222f310ebfe.png">

**Comment by IAlferink** [comment]
@yf508 Can we remove the _Language being learnt_ and _Type /purpose of resource_. 
<img width="1313" alt="Screenshot 2019-08-29 at 10 02 10" src="https://user-images.githubusercontent.com/40735172/63926724-378bb380-ca44-11e9-8e73-1478e3058b6e.png">

**Comment by yf508** [comment]
@IAlferink thanks for testing. It's fixed.
