### ISSUE TITLE
Change which collections appear on homepage

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#193]
Can we change which collections appear in the box on the homepage? At the moment it looks like you see the 5 collections that were created first (i.e. the oldest). Would it be possible for us to specify which ones appear there (like the feature option)?

<img width="1322" alt="Screenshot 2019-08-22 at 12 02 06" src="https://user-images.githubusercontent.com/40735172/63754325-97e7ed00-c8ac-11e9-8c95-1647a60c226d.png">

**Comment by IAlferink** [comment]
@yf508 Does Hyrax support displaying _modified last_ instead of _created first_? If it does that could maybe be an interim solution

**Comment by yf508** [comment]
@IAlferink I don't think Hyrax directly support the displaying order but I think it won't be hard to implement that.

**Comment by IAlferink** [comment]
@yf508 Ok, so eventually I would like it if we could choose what appears there. We have a nested structure and it would be good if the top levels would show there. In the meantime if you can easily implement _modified last_ that would be good.

**Comment by WendyEBurns** [comment]
see homepage doc v3 for update - https://drive.google.com/file/d/19q823MzdaXzUvMGFDKUCSltr_ZNoxyZd/view?usp=sharing

**Comment by paluchas** [comment]
Resolved during winter 2020/21 sprint.
