### ISSUE TITLE
Make 'parent collection' less prominent

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#194]
Could we please make the 'parent collection' a bit more subtle? Sitting between the description and works doesn't make sense to me. It breaks the flow and is too prominent.

<img width="1395" alt="Screenshot 2019-08-27 at 09 40 25" src="https://user-images.githubusercontent.com/40735172/63755620-ed24fe00-c8ae-11e9-8578-94f84a605274.png">

**Comment by IAlferink** [comment]
@websnacks Maybe you have ideas about the aesthetics?

**Comment by yf508** [comment]
@IAlferink How about swap it with Works:

![image](https://user-images.githubusercontent.com/437701/63857725-21c2b380-c99c-11e9-8807-3f858c5140a6.png)

**Comment by IAlferink** [comment]
@yf508 Yes, I think that could work

**Comment by IAlferink** [comment]
The text moves depending on whether there is one page (2) or more than one page (1). Can you make it so the text always appears on the left?
1.
<img width="1279" alt="Screenshot 2019-08-29 at 09 55 51" src="https://user-images.githubusercontent.com/40735172/63926403-b16f6d00-ca43-11e9-9bde-70420c0f4a14.png">

2.
<img width="1249" alt="Screenshot 2019-08-29 at 09 59 05" src="https://user-images.githubusercontent.com/40735172/63926423-b92f1180-ca43-11e9-94df-b4322f65ce84.png">

**Comment by yf508** [comment]
@IAlferink the problem has been fixed and should be deployed to test server shortly.
