### ISSUE TITLE
Text description has disappeared from public view of collection

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#203]
The public view of a collection (1) does not show the text description I have entered (2). I has been. visible on the test site at an earlier point (3). Can you please fix this?
(1)
<img width="1234" alt="Screenshot 2019-09-02 at 15 58 51" src="https://user-images.githubusercontent.com/40735172/64122926-e01a7a00-cd9a-11e9-8a42-9b891ecc09a2.png">
 
(2)
<img width="1147" alt="Screenshot 2019-09-02 at 15 59 14" src="https://user-images.githubusercontent.com/40735172/64122978-fc1e1b80-cd9a-11e9-8f71-a5d1160ecc2d.png">

(3)
<img width="1374" alt="Screenshot 2019-08-22 at 12 02 52" src="https://user-images.githubusercontent.com/40735172/64123055-338cc800-cd9b-11e9-8c08-f6a16eb1782c.png">

**Comment by yf508** [comment]
@IAlferink fixed and deployed on test for reviewing.

**Comment by IAlferink** [comment]
@yf508 Works fine on test now
