### ISSUE TITLE
Download survey: Change "which country are you from" to optional

### ISSUE THREAD

**Issue by paluchas** [digital-york/ncelp#209]
This has been requested by EM. This change will revoke some changes as done for #166 with #186

**Comment by IAlferink** [comment]
@paluchas I was talking to Emma yesterday. Could you tell me how long this would take to do?

**Comment by websnacks** [comment]
Done. I removed the `(optional)` text from Email as well, since all fields are now not required.
I am not sure what to do with the next popup which says:

Thank you. The information you entered has been saved successfully.

Seems to me like an extra step which could be removed.

**Comment by IAlferink** [comment]
@websnacks I think the occupation one is compulsory (it should be)? And yes, if the last pop up is not necessary, please remove. Fewer steps is better :-)

**Comment by websnacks** [comment]
Yes correct, let me take a look again at this.
