### ISSUE TITLE
Collapse metadata

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#218]
Can we change the _Resource Details_ page, so that we 
1. Keep the title and the description?
2. Collapse the other information under a button called _About this resource_
<img width="1336" alt="Screenshot 2019-10-09 at 12 56 00" src="https://user-images.githubusercontent.com/40735172/66479522-99ecc080-ea94-11e9-8ec5-908b89709744.png">

**Comment by websnacks** [comment]
Work completed, ready for going to staging.
