### ISSUE TITLE
Make selection boxes in upload form bigger

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#221]
To make the uploading process easier, could we make the boxes where you select the terms bigger. This would be for the facets _topic_ and _pedagogical focus_.

<img width="1270" alt="Screenshot 2019-10-17 at 11 07 11" src="https://user-images.githubusercontent.com/40735172/66999765-8235bd80-f0ce-11e9-9d84-32b6b42c2798.png">

**Comment by websnacks** [comment]
Done - created pull request into development.

**Comment by IAlferink** [comment]
@websnacks Just wanted to say that I'm going to make the same request for OASIS. It's not urgent, but just so you know.
