### ISSUE TITLE
Update Contact page - remove contact form and replace with text

### ISSUE THREAD

**Issue by WendyEBurns** [digital-york/ncelp#224]
Can we remove the contact form and replace with text.

### Contact us

**For general Resource Portal enquiries and feedback:**
Email: resources@ncelp.org
Telephone: 01904 328159

**To report a problem or to request help in using the system:** 
Please first visit the 'Help' page. If your query is not answered there, email us at resources@ncelp.org with details and one of the team will get back to you.

**Postal address:**
National Centre for Excellence for Language Pedagogy (NCELP)
Department of Education
University of York
York
YO10 5DD

**Mailing list:** 

If you would like to receive a regular bulletin of the latest materials added to the NCELP Resource Portal as well updates on the Centre’s activities, sign up to our [mailing list](https://docs.google.com/forms/d/e/1FAIpQLSeJy-sMKW_1qQQMJWxatdS_FBS2a8IMIBT_XOSoNf9nvsCb_w/viewform).

**Comment by websnacks** [comment]
Done, waiting for code review and merge into development.
