### ISSUE TITLE
Download report

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#225]
We would like to have a way to access information about how the Resource Portal is being used. Specifically, we want to be able to track downloads and have an efficient way of accessing this information. Partly, this is for our own understanding of which materials are being used, but also for our funders.

Create an accessible way to see / create a regular download report with the following information (possibly related to [206](https://github.com/digital-york/ncelp/issues/206)):

- General information
1. How many resources
2. How many total downloads (number)
3. How many total downloads over time (visualisation nice, but not priority)

- Breakdown of total downloads by the download survey (who is downloading our resources)

- How many downloads per category

1. Age range (Y7, Y8, etc)
2. Language (French, German, etc)
3. Type / purpose of material (Classroom material, Material for teachers, Assessments, etc.)
4. Pedagogical focus (Phonics, Vocabulary, etc.)
5. Materials for teachers (SOW, CPD, etc. )

- Downloads per resource (totals only - over time not crucial)

**Note**
Total downloads at the moment means unique user downloads per 30 days as the number is tethered to the download survey. This likely underreports usage as users might download multiple resources per month. This is quite likely, especially from teachers using our scheme of work and associated teaching materials. Counting the number of downloads without reference to the survey is not useful as that will include a large number of crawlers /bots. Frank is looking at options to get a more accurate number.

**Comment by IAlferink** [comment]
I've asked Emma and Minna to review the categories. Document [here](https://docs.google.com/document/d/14R4M7BusoxxMwsIhAzWLroZv4VMal1CRN7WAfdT8K0Q/edit?usp=sharing). I'll update the issue description when confirmed.

**Comment by IAlferink** [comment]
@yf508 The downloads per resource can be totals rather than over time.

**Comment by paluchas** [comment]
Resolved with winter 2020/21 sprint
