### ISSUE TITLE
Change buttons on the homepage

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#275]
Now that we have the collections option available, we want to draw a bit more attention to some of the more frequently used ones. I have had a look at the google analytics for how people use the buttons and I think we can get away with repurposing some of them to link to the top level of the scheme of work collections for each language. Other ideas are welcome!

Change the current configuration to:
Top row (stays orange): All resources - Type / purpose of resource - language being learnt - pedagogical focus
Bottom row (change to blue): All collections - [SOW French](https://resources.ncelp.org/collections/t148fh31r?locale=en) - [SOW German](https://resources.ncelp.org/collections/k3569444k?locale=en) - [SOW Spanish](https://resources.ncelp.org/collections/f1881m10k?locale=en)

![image](https://user-images.githubusercontent.com/40735172/70335063-7baa0380-183e-11ea-9a2d-caf40a7d0dc2.png)

**Comment by IAlferink** [comment]
@WendyEBurns Did you have additional suggestions for making the homepage more user friendly? The featured works doesn't seem to be used much.

**Comment by WendyEBurns** [comment]
> @WendyEBurns Did you have additional suggestions for making the homepage more user friendly? The featured works doesn't seem to be used much.

I will do a mock up early October - or sooner if needed - of a revamped homepage. It won't be new functionality - just changes to boxes, buttons with links (and I'll keep changes to a minimum) so hoping it will be straightforward to do. Things have moved on a long way since launch and we need to highlight our fully resourced schemes of work which is our main offering.

**Comment by WendyEBurns** [comment]
See latest homepage doc v3- https://drive.google.com/file/d/19q823MzdaXzUvMGFDKUCSltr_ZNoxyZd/view?usp=sharing
