### ISSUE TITLE
Clean temporarily uploaded files

### ISSUE THREAD

**Issue by paluchas** [digital-york/ncelp#283]
# Issue
We have build up on disk space with temporary uploaded files e.g. 
```
../current/tmp/uploads/hyrax/uploaded_file/file
``` 

# Proposed solution
1. Use Figaro to set [config.working_path]( https://github.com/digital-york/ncelp/blob/bcd93908a0dffc62c08e8962d9c13a6ec08a8d53/config/initializers/hyrax.rb#L207 ) variable
2. Configure working_path to _/tmp/hyrax/uploads_
3. Develop automation to clan all uploaded temporary files withing given time.

**Comment by Jimadine** [comment]
@paluchas Point 3 of the Proposed solution was done in puppet, see git commit ref `e88de69` (Mon May 4 12:43:55 2020 +0100). Please let me know if you think there is further work to be done.
