### ISSUE TITLE
How to cite NCELP

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#304]
**Note IA: Info from Emma. I will edit request later, once we've had a change to discuss** We have how to cite for OASIS.
@Wendy - this is a really good & timely question. Could we put a statement and example (with formatting as below) clearly at the top of the portal about this, in biggish, coloured? letters
Some of the information could be hidden under clickable button perhaps?

How to cite material available on the NCELP Resources Portal

If you wish to cite material from NCELP, please use the following in-text citation format, illustrated here: 

"..., as suggested by NCELP (2019). It has also been proposed that grammar can be taught in small discrete units (NCELP, 2020a). Furthermore, NCELP (2020b) recommends that vocabulary should be regularly revisited." 

For the full reference, please use the following format: 

NCELP (year given on the resource itself. If this is not available, use 2019). Title of the resource. National Centre for Excellence for Language Pedagogy: University of York, UK. Retrieved from [url] [date it was downloaded in this format: 20 November 2020].
For example,
NCELP (2020). Meaningful practice: definitions, rationale and principles. National Centre for Excellence for Language Pedagogy: University of York, UK. Retrieved from https://resources.ncelp.org/concern/resources/ng451h506?locale=en on 20 November 2020. 

Note: Sometimes individual authors are listed on some of the materials, and those authors' names can be used instead of 'NCELP'. For the in-text citation, this would be "Kasprowicz (2020)". For the reference this would be "Kasprowicz, R. (2020)". [followed by the reference as above]. However, most of the time "NCELP" as the author is the most appropriate.

**Comment by IAlferink** [comment]
@WendyEBurns Can you add the discussion you had with Emma here as well?

**Comment by WendyEBurns** [comment]
Updated 'Changes to Homepage docv3'- https://drive.google.com/file/d/19q823MzdaXzUvMGFDKUCSltr_ZNoxyZd/view?usp=sharing' to include new page with text and request for a link on the homepage for 'How to cite material'. 
NCELP team to add the page link on About/Help/Collections pages etc.

**Comment by paluchas** [comment]
Resolved https://resources.ncelp.org/cite
