### ISSUE TITLE
Clicking on 'other' does not open up text field

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#50]
Clicking the other option does not open up a text field for me for
- Language being learnt
- Pedagogical focus
- Material for teachers

**Comment by yf508** [comment]
It looks like a browser compatibility issue. Cannot reproduce the problem in Chrome 72.0.3626.121 and Firefox 65.0.2 (64-bit) on Windows PC.

**Comment by IAlferink** [comment]
@yf508 Yes, I used Safari (Version 12.0 (14606.1.36.1.9)). Similar to the issue with OASIS.

**Comment by paluchas** [comment]
Review and apply fixes as per OASIS [PR357](https://github.com/digital-york/oasis/pull/357)

**Comment by paluchas** [comment]
It works as expected on Chrome, Firefox and Safari.
