### ISSUE TITLE
Recently uploaded box - remove depositor

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#53]
Can we remove the Depositor from the Recently Uploaded box on the home page?

Question: What do the key words do? Can we replace the placeholder (like for the top two items below) with something else?
<img width="389" alt="Screenshot 2019-03-22 at 17 17 53" src="https://user-images.githubusercontent.com/40735172/54841103-74e65b00-4cc6-11e9-9d7b-a5d2f8bfb052.png">

**Comment by yf508** [comment]
@IAlferink Yes, sure we can add any data we like, for now, I've added topics there.
