### ISSUE TITLE
Facet list is incomplete

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#54]
Not all relevant facets are present in the facet list on the left hand. Missing are:
- Language being learnt
- Material for teachers
- Modality / mode (skill)

In addition, _The theme of resource_ should be named _Topic_.

<img width="429" alt="Screenshot 2019-03-22 at 17 20 28" src="https://user-images.githubusercontent.com/40735172/54841258-d1497a80-4cc6-11e9-9efc-845da40816a4.png">

**Comment by yf508** [comment]
The current implementation is just a reflection of the facets listed in [this doc](https://docs.google.com/spreadsheets/d/1nLGNtMHv_p1r8TAlGtnvuyNw-wTcu00-7wjcmtbeqhQ/edit#gid=0). @IAlferink please add the new facets into the doc so I know the order of them?

**Comment by IAlferink** [comment]
@yf508 I'm having trouble accessing the google at the moment. It keeps not loading. I'll try again in a bit.

**Comment by IAlferink** [comment]
@yf508 Facet order has now been updated in the google spreadsheet.

**Comment by IAlferink** [comment]
@yf508 Modality / mode (skill) is not in the facet list yet, but I think there was another issue for that?

**Comment by yf508** [comment]
Yes, it's #79 I think it's nothing wrong with facet. the problem was caused by the missing data.
