### ISSUE TITLE
Fix alignment in left hand facet list

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#83]
In the search results the > in the top facet is misaligned.
<img width="320" alt="Screenshot 2019-03-28 at 14 14 00" src="https://user-images.githubusercontent.com/40735172/55164605-d80f3c00-5163-11e9-8982-fbdfbad297da.png">

**Comment by yf508** [comment]
tested in Chrome/Firefox but cannot reproduce this problem.

**Comment by IAlferink** [comment]
@yf508 this seems to be a Safari thing again. I don't have the issue in Chrome.

**Comment by paluchas** [comment]
I do remember seeing this. Just tested again on Chrom and Safari. Tried to increase font size. It works as expected. Perhaps the summer sprint introduced some change to styling that helps with this one.

**Comment by paluchas** [comment]
We can reproduce it now.

**Comment by websnacks** [comment]
This issue is not resolved and already pushed to live.
