### ISSUE TITLE
Facet pages - clicking the previous /next button doesn't do anything

### ISSUE THREAD

**Issue by IAlferink** [digital-york/ncelp#97]
Clicking on the previous / next button on the facet pages doesn't seem to do anything.
<img width="534" alt="Screenshot 2019-03-29 at 11 58 37" src="https://user-images.githubusercontent.com/40735172/55231337-35fe5b00-521a-11e9-8de3-842ffeca8c80.png">

**Comment by yf508** [comment]
It's not a bug, the 'previous' / 'next' only appear whenever they are needed, e.g. in the screen dump provided, there are only 6 records so no previous/next page at all. The current test server has enough records to make these buttons available:

![image](https://user-images.githubusercontent.com/437701/55390346-ee841180-552e-11e9-8f55-ee42a243feb8.png)

![image](https://user-images.githubusercontent.com/437701/55390367-fa6fd380-552e-11e9-8ea6-e05c2dd12f42.png)

@IAlferink Pls feel free to reopen this issue if I misunderstood.

**Comment by IAlferink** [comment]
@yf508 No, you understood correctly. Thanks :-)
